bot:
  token: ${BOT_TOKEN}
  username: "@ReminderManagerBot"
  url: https://3d80-185-154-73-126.ngrok-free.app

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_manager_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql=true
    ddl-auto=update